### ISSUE TITLE
[bug]: Install script don't complete successfully

### ISSUE THREAD

**Issue by stefanodemartini** [FreePBX/sng_freepbx_debian_install#106]
### FreePBX Version

FreePBX 17

### Issue Description

Installed a fresh version of Debian 12 and run the install script with flag --dahdi.
The script ends prematurely  and the relevant raw of the log has the following content:

`E: Unable to locate package dahdi-linux-kmod`

The following command is indicated to check manually the current kernel version and in the script is used to identify the current kernel version and set  variables in the script itself. 

`apt-cache show linux-headers-$(uname -r) | sed -n -e 's/Package: linux-headers-\\([[:digit:].-]*\\).*/\\1/' -e 's/-\$//p' | uniq`

If  you run once above you notice that the result is empty.

### Operating Environment

Debian 12
Kernel  6.1.0-23-amd64

### Relevant log output

```shell
`E: Unable to locate package dahdi-linux-kmod`
```

**Comment by JoseGoncalves** [comment]
Or I'm missing something, or the command that the script is currently using to extract the kernel version seems a bit overkill (besides it seems not to be working).

IMHO, something simpler as the following would do the trick:
```bash
local curr_kernel_version=$(uname -r | cut -d'-' -f1-2)
```

**Comment by stefanodemartini** [comment]
change all occurrences of 
`apt-cache show linux-headers-$(uname -r) | sed -n -e 's/Package: linux-headers-\\([[:digit:].-]*\\).*/\\1/' -e 's/-\$//p' | uniq`
with 
`uname -r | cut -d'-' -f1-2` 
as suggested by JoseGoncalves and now it works like a charm. 
I'm suggesting to commit this change to the official script.
