### ISSUE TITLE
[new-feature]: make chrony install optional

### ISSUE THREAD

**Issue by hknet** [FreePBX/sng_freepbx_debian_install#119]
### FreePBX Version

FreePBX 17

### Feature Description

it would be useful for container setups to make the chrony package an option one could disable when starting the setup-script.
therefore I'd ask for an option like "--disable-chrony" for the install-script.

**Comment by jaminmc** [comment]
It works with Pull Request #122 

Just replace step 2 with:
```bash
wget https://raw.githubusercontent.com/jaminmc/sng_freepbx_debian_install/refs/heads/patch-1/sng_freepbx_debian_install.sh -O /tmp/sng_freepbx_debian_install.sh
```

You may need to add `--skipversion` to it if the version check doen't allow it to install.
