### ISSUE TITLE
[bug]: PHP 8.2 is not available out of the box on Ubuntu 22.04.4 LTS

### ISSUE THREAD

**Issue by tdltdl** [FreePBX/sng_freepbx_debian_install#12]
### FreePBX Version

FreePBX 16

### Issue Description

When running script on Ubuntu 22.04.4 LTS, it fails with error "Exiting the installation process as dependent php8.2 failed to install ...."

### Operating Environment

Ubuntu 24.04.4LTS

### Relevant log output

```shell
Installing php8.2 Now ....
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php8.2
E: Couldn't find any package by glob 'php8.2'
E: Couldn't find any package by regex 'php8.2'
```

**Comment by tdltdl** [comment]
See https://php.watch/articles/install-php82-ubuntu-debian for solution (being fixed as part of https://github.com/FreePBX/sng_freepbx_debian_install/issues/4

**Comment by chrsmj** [comment]
The install target is Debian 12 not Ubuntu.

**Comment by tdltdl** [comment]
I was not aware of this. Ubuntu being Debian based, I thought it was cool to have FreePBX running on Ubuntu too (and it seems to work at first sight). If really the only platform is Debian 12, then maybe adding a check when the install script start could make it explicit.

**Comment by kguptasangoma** [comment]
@tdltdl added Ubuntu repo to download php 8.2 in the latest script hence closing this jira. thanks
