### ISSUE TITLE
[bug]: Dashboard reports that system is only set up for 1000 variables when not true

### ISSUE THREAD

**Issue by AlanCham56** [FreePBX/sng_freepbx_debian_install#124]
### FreePBX Version

FreePBX 16

### Issue Description

Dashboard provides error "Your system is setup to only handle 1000 variables. This is not enough to handle the number of devices you have. You should increase this to at least 5000. CLick Resolve for instructions to fix".  Following instructions to resolve the issue, php.ini was properly set and confirmed in PHP Info Report.  Per the report: max_input_vars=5000.   I clear the error and within 24 hours, it returns.  Restarts and reboots do not change symptoms.   

### Operating Environment

PBX Version:   17.0.19.12
PBX Distro:      12.7.8-2402-3.sng12
Asterisk Version:   21.4.3
[moduleslist.txt](https://github.com/user-attachments/files/17169016/moduleslist.txt)
![image](https://github.com/user-attachments/assets/a735824d-552f-4d9b-b35f-08a89eb5b212)

**Comment by lgaetz** [comment]
Hi Alan

This desktop notification is generated by the ClearlyIP Devices module. This is not a Freepbx issue.

CIP will resolve this thru their ticketing system.
