### ISSUE TITLE
[bug]: The following packages have been kept back: freepbx17

### ISSUE THREAD

**Issue by Bloodpack** [FreePBX/sng_freepbx_debian_install#132]
### FreePBX Version

FreePBX 17

### Issue Description

when i do a upgrade via `apt update && apt upgrade -y && apt autoremove -y`

i get this messgage in the console `The following packages have been kept back: freepbx17`

maybe the package can be removed from the package list

### Operating Environment

Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

### Relevant log output

```shell
root@freePBX:~# apt update && apt upgrade -y && apt autoremove -y
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm-updates InRelease
Hit:3 http://ftp.debian.org/debian stable InRelease
Hit:4 http://security.debian.org/debian-security bookworm-security InRelease
Hit:5 http://deb.freepbx.org/freepbx17-prod bookworm InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  freepbx17
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

**Comment by JoseGoncalves** [comment]
This is normal behaviour. There are some packages provided by Sangoma (including freepbx17) that are to be used only for initial setup and cannot be upgraded after.

**Comment by Bloodpack** [comment]
yes i understand this...

can this package be removed from the package list, so that no one gets confused and maybe do some stupid things and breaks his pbx...

**Comment by Bloodpack** [comment]
@JoseGoncalves thanks for the clarification
