### ISSUE TITLE
[improvement]: Install ending with 2024-11-03 20:21:18 - Installing postfix

### ISSUE THREAD

**Issue by TigerIS2025** [FreePBX/sng_freepbx_debian_install#137]
### FreePBX Version

FreePBX 17

### Improvement Description

Hi, i am tiger, a shell coder, a BBC fan (i dont live in uk) and  a FreePBX fan. I am new to freepbx and i am trying to  install  17. Anyways, i have a issue:  Installaton ending with 2024-11-03 20:21:18 - Installing postfix .... and it exits the script.  
> Note: I am on the WSL Debain 12 Linux and i am trying to install 17.

Log: 

```
Running newaliases
newaliases: fatal: bad string length 0 < 1: mydomain = 
dpkg: error processing package postfix (--configure):
 installed postfix package post-installation script subprocess returned error exit status 75
Processing triggers for rsyslog (8.2302.0-1) ...
invoke-rc.d: unknown initscript, /etc/init.d/rsyslog not found.
invoke-rc.d: could not determine current runlevel
Errors were encountered while processing:
 postfix
E: Sub-process /usr/bin/dpkg returned an error code (1)
2024-11-03 20:21:27 - Exiting script
```

**Comment by TigerIS12024** [comment]
I think  i figured it out, i need to edit the configuration file and add the mydomain. Other errors to fix?
