### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by softwarecrash** [FreePBX/sng_freepbx_debian_install#142]
### FreePBX Version

FreePBX 17

### Issue Description

after following the installation instruction here https://sangomakb.atlassian.net/wiki/spaces/FP/pages/295403538/Step+By+Step+Debian+12+Installation
everthing runs fine, until the machine is rebooted, then freepbx is not reachable over web.
fwconsole start or restart dindt help, only runs the installer script again brings the freepbx back again

### Operating Environment

Debian 12

### Relevant log output

```shell
[    4.624404] systemd[1]: freepbx.service: Found ordering cycle on apache2.service/start
[    4.624411] systemd[1]: freepbx.service: Found dependency on freepbx.service/start
[    4.624417] systemd[1]: freepbx.service: Job apache2.service/start deleted to break ordering cycle starting with freepbx.service/start
```

**Comment by kguptasangoma** [comment]
please try to modify the freepbx.service and httpd.service as mentioned in the below comment 
https://github.com/FreePBX/issue-tracker/issues/496#issuecomment-2464470128 

We will soon update the freepbx debian package to take care of this. 
thanks

**Comment by softwarecrash** [comment]
thanks for the realy fast answer, i try this modicifation.
the apache2 error is not showing anymore but the freepbx is not reachable.
but after start and login over ssh systemctl start apache2.service brings back the web pages

**Comment by sharlow** [comment]
This and all the related issues like https://github.com/FreePBX/issue-tracker/issues/496 all seem to be closed but it doesn't seem like the change actually made it to release, I have run in to this same issue just now on a brand new install.
