### ISSUE TITLE
[improvement]: Make it clear that the server should be blank or that you need apache. Otherwise make it possible to use nginx

### ISSUE THREAD

**Issue by DDQW** [FreePBX/sng_freepbx_debian_install#144]
### FreePBX Version

FreePBX 17

### Improvement Description

i just ran the script on debian12 with existing nginx installation and several sites. it changes owndership of var/www/html and nuked severral services for a few minutes (thankfully was easily fixed by chown)

the readme should reflect that this can happen.

it also could use a cleanup script in case of failure and maybe some options what to put where.

**Comment by kguptasangoma** [comment]
Hi @DDQW okay, will update the readme. 

We have not tested Freepbx with NGINX hence as of now can not offer freepbx to work with nginx and depends on apache for web services.

thanks

**Comment by DDQW** [comment]
Thats great. 

I wonder if you could provide a sample apache config so that some people who are willing to experiment a bit could try to make it work with nginx.
