### ISSUE TITLE
[improvement]: Remove unneeded packages

### ISSUE THREAD

**Issue by tdltdl** [FreePBX/sng_freepbx_debian_install#15]
### FreePBX Version

FreePBX 17

### Improvement Description

The current script installs weird packages (to list a few
- nmap
- tcpdump
- openvpn
- dpkg-dev
- build-essential (and other build and dev related packages)
- git
- subversion
- htop
- ...)

I do not believe anything is checkout and built during installation or normal operation of the PBX.

Adding unnecessary packages increase the security risk and the maintenance cost (more packages to install and keep updated)

**Comment by vladdevops** [comment]
Hi.
And  `ioncube-loader-82`

**Comment by kguptasangoma** [comment]
We need those tools to help us in debugging for example tcpdump , openvpn , ioncube for commercial modules.

I can understand, may not be good for a normal open source Freepbx operation but required for a commercial modules or for debugging purposes.

**Comment by tdltdl** [comment]
Why don't you add a parameter then or at least split the list in 2?
And even if you "need it for the commercial support" I really doubt you need both SVN and git for example (and as per my other ticket allowing MD5 in openvpn is not a very sign of security consciousness for your paid customers ;-) ).

**Comment by kguptasangoma** [comment]
` split the list in 2?` we could think to do this to bifurcate installing commercial components with opensource. 

openvpn is required for VPN support which is required if customer wants to use the VPN.
