### ISSUE TITLE
[bug]: Sangoma-pbx17 includes config files from other packages.

### ISSUE THREAD

**Issue by tdltdl** [FreePBX/sng_freepbx_debian_install#16]
### FreePBX Version

FreePBX 17

### Issue Description

sangoma-pbx17 (2402-3.sng12) is including configurations from other packages (fail2ban).
This should not be the case.
Other config are suspicious (like re-enabling MD5 in openvpn)

### Operating Environment

Ubuntu 22.04.4 LTS but valid for any

### Relevant log output

```shell
Unpacking sangoma-pbx17 (2402-3.sng12) ...
dpkg: error processing archive /var/cache/apt/archives/sangoma-pbx17_2402-3.sng12_all.deb (--unpack):
 trying to overwrite '/etc/fail2ban/action.d/iptables-allports.conf', which is also in package fail2ban 0.11.2-6
```

**Comment by kguptasangoma** [comment]
We are coping the config files what is required for the FreePBX which for sure will overwrite the system generated files, hence you are seeing this conflict.

this is mainly to ensure that , after script execution system should start working as a FreePBX with all the default configurations setup. 

thanks

**Comment by tdltdl** [comment]
Can we then have 2 pkg install, one that do not allow overwrite for all "sane" packages and a dedicated one for FreePBX that includes those "weird" behaviour?

**Comment by kguptasangoma** [comment]
yes we could do that.
