### ISSUE TITLE
[bug]:

### ISSUE THREAD

**Issue by aidajulia** [FreePBX/sng_freepbx_debian_install#20]
### FreePBX Version

FreePBX 17

### Issue Description

"FreePBX 17 Script for Raspberry Pi" 
Hello everyone, your scripts for FreePBX 17 are a great job!  🏅

My question may also be a suggestion 😂
At the moment is it possible to get a similar script like this for Raspberry Pi?

On platforms, ARM needs your help!
I think the RasPBX project is dead.
"RasPBX no longer receives support or updates from its author"

Right now the Raspberry Pi has excellent support for the headless Debian 12 operating system, and this is low-cost hardware for very small systems and great for training and development purposes.

Please think about this, many people would appreciate it.

### Operating Environment

Raspberry Pi OS Lite
Release date: March 15th 2024
System: 64-bit
Kernel version: 6.6
Debian version: 12 (bookworm)
Size: 414MB

**Comment by doczkal** [comment]
Thanks for posting. I was hoping to get the Asterisk + freePBX running on a Raspberry Pi just like you.

**Comment by kguptasangoma** [comment]
Hi @aidajulia right now our focus is to have up and running Freepbx 17 on Debian.
