### ISSUE TITLE
[improvement]: Script FreePBX 17 OPEN to channel driver

### ISSUE THREAD

**Issue by aidajulia** [FreePBX/sng_freepbx_debian_install#29]
### FreePBX Version

FreePBX 17

### Improvement Description

Is it possible to create in the new FreePBX 17 script a compatibility option similar to the DAHDI option provided, but in this case for the Chan-SIP channel driver?  

This is important for technological reasons, and is totally optional for those who require it due to migration aspects.  

Giving this option accelerates adoption in certain environments very surely.  
thank you!
Great Work!

**Comment by kguptasangoma** [comment]
Hi @aidajulia "Chan-SIP channel driver" means? Could you please elaborate the requirements in bit detail ?

Migration will happen via backup and restore , script is only useful to  perform the initial setup of the system.

We are adding option in Backup & Restore to convert chansip extensions to pjsip during the restore process to ease the migrate if the running version is asterisk 21 (which do not support chan_sip).

**Comment by aidajulia** [comment]
The requirement is not directly related to migrating existing configuration via Backup/Restore, but rather to being able to migrate clients from previous versions to Asterisk 20 and continue to be compatible with other product developments (3rd party products) that have development with AMI and are based on AMI Events with Chan-SIP Channel Driver.

 In this way, it is possible to initially migrate/update the Asterisk and FreePBX environment to the most recent FreePBX environment, while still offering compatibility with development products such as CTI / TAPI / CSTA but with AMI, and that are operating with Driver Chan-SIP Channel.

In this way it is possible to update Asterisk and FreePBX and you can still have a legacy 3rd party product working, until then we can update the Chan-SIP Channel Driver in the next version.

**Comment by lgaetz** [comment]
Hi @aidajulia 

chan_sip is not a project priority at this point. FreePBX 17 does support chan_sip, but Asterisk 21 does not. If you wish to downgrade asterisk to version 20, that is supported using the `asterisk-version-switch` script and continue to use chan_sip, that should work.

We will try not to do anything to break chan_sip support in FreePBX 17, but no new work will be done to support it.

**Comment by aidajulia** [comment]
Thank you!
