### ISSUE TITLE
[improvement]: Disable fail2ban default

### ISSUE THREAD

**Issue by yopaz-quanlv** [FreePBX/sng_freepbx_debian_install#37]
### FreePBX Version

FreePBX 16

### Improvement Description

Freebpx fail2ban automatically block my ip when i connect via SIP.
I think fail2ban should be disabled as default. 

Source : https://www.freepbxhosting.com/how-to-help-ive-been-blocked-from-my-pbx/

**Comment by kguptasangoma** [comment]
hey @yopaz-quanlv please provide bit more detail about the issue for us to reproduce in-house?
also is this freepbx 16 or freepbx 17?

**Comment by yopaz-quanlv** [comment]
It's ok. 
I will disable it by custom script.
