### ISSUE TITLE
[bug]: script stopping immediately after saying "Perfect! You're already running the latest version."

### ISSUE THREAD

**Issue by rabreu95** [FreePBX/sng_freepbx_debian_install#45]
### FreePBX Version

FreePBX 17

### Issue Description

When I try running the script on a fresh copy of Debian 12 running on Proxmox, It first outputs "Performing version check..." then "Perfect! You're already running the latest version." then goes right back to the shell prompt with out doing anything. 

### Operating Environment

Debian 12.5.0 on Proxmox.

**Comment by kguptasangoma** [comment]
Hi @rabreu95 We have tested Digital ocean, Vultr, AWS or local vm machines and working fine, so not sure if proxmux not liking any of the script syntax.

Can you please try to edit the script to add some prints to see what could be wrong?

**Comment by ramarajan222** [comment]
Hi @rabreu95 Are you using container or VM ? Can you check you check the installation logs, it might give some info about where exactly the script has exited.

**Comment by kguptasangoma** [comment]
Hi @rabreu95 Can you please give a try with the latest script and let us know the result ? if still not working please share the installation logs. thanks
