### ISSUE TITLE
[bug]: install script disables IPv6

### ISSUE THREAD

**Issue by billsimon** [FreePBX/sng_freepbx_debian_install#5]
### FreePBX Version

FreePBX 17

### Issue Description

https://github.com/FreePBX/sng_freepbx_debian_install/blob/master/sng_freepbx_debian_install.sh#L401-L407

Installer disables IPv6.

### Operating Environment

Debian 12

**Comment by chrsmj** [comment]
Is a better temporary fix for nodejs localhost issue to add this line to /etc/gai.conf:

`precedence ::ffff:0:0/96  100`

**Comment by billsimon** [comment]
@kguptasangoma can we get ipv6 enabled here taking into consideration the workaround suggested by @chrsmj?

**Comment by kguptasangoma** [comment]
Hi @billsimon removed the ipv6 disable logic from the script as @chrsmj suggested workaround to give ipv4 precedence looks working fine. Ref-https://github.com/FreePBX/sng_freepbx_debian_install/pull/48
