### ISSUE TITLE
[bug]: sng_freepbx_debian_install script sudo errors

### ISSUE THREAD

**Issue by arielgrin** [FreePBX/sng_freepbx_debian_install#52]
### FreePBX Version

FreePBX 17

### Issue Description

The FreePBX 17 install scripts has several lines executing sudo commands, but the script is supposed to be run as root so sudo should not be needed, even more taking into consideration that a minimal Debian 12 netinstall install does not ship with sudo installed.

### Operating Environment

Debian 12.5

FreePBX 17 install script version 2d41246

### Relevant log output

```shell
root@freepbx:/tmp# ./sng_freepbx_debian_install.sh --dahdi
./sng_freepbx_debian_install.sh: line 25: sudo: command not found
Performing version check...
Perfect! You're already running the latest version.

The following lines have sudo commands

Line 25: echo 'export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' | sudo tee -a /root/.bashrc > /dev/null

Line 595: sudo apt-mark hold "$pkg"
```

**Comment by kguptasangoma** [comment]
Hi @arielgrin Thanks for reporting this issue, I have removed the usage of "sudo" and updated the script.

Thank you for using FreePBX 17
Kapil

**Comment by digdug3** [comment]
Thank you
