### ISSUE TITLE
Installation script v1.3 with 12.5 Debian image failed to locate package mongodb-org

### ISSUE THREAD

**Issue by Stevehans** [FreePBX/sng_freepbx_debian_install#53]
### FreePBX Version

FreePBX 17

### Issue Description

Ran the installer, but it ended with unable to locate package mongodb-org

Will investigate why, but this was a clean install of the DVD image from debian.org followed by a wget of the script and execution

### Operating Environment

Debian 12.5 DVD image
Latest v1.3 of installer script

### Relevant log output

```shell
2024-06-10 16:38:38 - Setting up MongoDB
2024-06-10 16:38:38 - Installing  mongodb....
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package mongodb-org
2024-06-10 16:38:38 - Exiting script
```

**Comment by kguptasangoma** [comment]
Hey @Stevehans  we are adding mongodb repo , so please check if that is setting properly to you or not. 
https://github.com/FreePBX/sng_freepbx_debian_install/blob/master/sng_freepbx_debian_install.sh#L217

**Comment by kguptasangoma** [comment]
"apt install mongodb-org"  what does this gives to you ?

**Comment by kguptasangoma** [comment]
also see what do you see in the log file, that may have some more information.

**Comment by Stevehans** [comment]
Here's the entry from the list file

```
deb [arch=i386] http://repo.mongodb.org/apt/debian bookworm/mongodb-org/7.0 main
# deb-src [arch=i386] http://repo.mongodb.org/apt/debian bookworm/mongodb-org/7.0 main


```

**Comment by kguptasangoma** [comment]
looks like mongodb somehow not installing on your system, can you please try to check if the repo is good or not?

**Comment by Stevehans** [comment]
Here's the issue, are you guys only running this on Raspberry Pis :) :-

```
root@freepbx17:/var/log/pbx# apt update
Hit:1 http://ftp.debian.org/debian stable InRelease
Hit:2 https://deb.debian.org/debian bookworm InRelease
Hit:3 https://packages.sury.org/php bookworm InRelease
Ign:4 http://repo.mongodb.org/apt/debian bookworm/mongodb-org/7.0 InRelease
Hit:5 http://repo.mongodb.org/apt/debian bookworm/mongodb-org/7.0 Release
Hit:6 http://deb.freepbx.org/freepbx17-prod bookworm InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://repo.mongodb.org/apt/debian bookworm/mongodb-org/7.0 InRelease' doesn't support architecture 'i386'
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://deb.freepbx.org/freepbx17-prod bookworm InRelease' doesn't support architecture 'i386'
root@freepbx17:/var/log/pbx#

```

**Comment by Stevehans** [comment]
Ah, just seen the amd64 image!

**Comment by Stevehans** [comment]
Don't use i386 images when you mean to use AMD64....

**Comment by kguptasangoma** [comment]
We are using like below to put arch.
	wget -qO - https://pgp.mongodb.com/server-7.0.asc | gpg  --dearmor --yes -o /etc/apt/trusted.gpg.d/mongodb-server-7.0.gpg >> "$log" 2>&1
      add-apt-repository -y -S "deb [ arch=${arch} ] http://repo.mongodb.org/apt/debian bookworm/mongodb-org/7.0 main" >> "$log" 2>&1
      
      What do you see output of "arch=`dpkg --print-architecture`" ?

**Comment by Stevehans** [comment]
Closed, my mistake, I'd used an i386 image not AMD64
