### ISSUE TITLE
[improvement]: be sure to validate installed binaries before using it

### ISSUE THREAD

**Issue by HLeithner** [FreePBX/sng_freepbx_debian_install#55]
### FreePBX Version

FreePBX 17

### Improvement Description

I would suggest to check for lsb_release and wget binary before using them

**Comment by kguptasangoma** [comment]
hi @HLeithner sorry , could you please explain bit more like why we need to check for lsb_release ?

**Comment by digdug3** [comment]
I had the same issue and had to `apt install lsb-release` before running the script.

**Comment by HLeithner** [comment]
@kguptasangoma we use our own down striped debian template vms which has no package installed we commonly don't need. So the lsb-release package and wget package is not installed.
to run the script I hardcoded "Debian" in the DISTRIBUTION variable and installed wget. 

Maybe it's common that lsb-release is available but maybe not always. Also instead of wget we have curl installed per default.

It's not a big issue but makes the script error safe.

**Comment by spessoni** [comment]
I had the same issue using a container on Proxmox (LXC). 

_debian-12-standard_12.2-1_amd64.tar.zst_ did not have _lsb-release_.

running `apt install lsb-release` allowed the script to continue.

**Comment by kguptasangoma** [comment]
Fixed in the latest version.

**Comment by AT-StephenDetomasi** [comment]
> I had the same issue using a container on Proxmox (LXC).
> 
> _debian-12-standard_12.2-1_amd64.tar.zst_ did not have _lsb-release_.
> 
> running `apt install lsb-release` allowed the script to continue.

How is the LXC version workin for you now? I have been looking into trying FreePBX 17 but I haven't heard of anyone trying an LXC install yet.
