### ISSUE TITLE
[improvement]: cloud-init.yaml instead of shell scripts

### ISSUE THREAD

**Issue by rajannpatel** [FreePBX/sng_freepbx_debian_install#57]
### FreePBX Version

FreePBX 17

### Improvement Description

Can we have cloud-init.yaml configuration templates, akin to what is found here: https://github.com/rajannpatel/ubuntupbx

This should make spinning up new Asterisk machines a breeze, especially on public cloud.

**Comment by kguptasangoma** [comment]
Thanks for your suggestion!

We're marking your suggestion as 'Patches Welcome'. This means that we're not, presently, going to be investigating the implementation of your suggestion, but we also agree that it has merit.

If you would like to implement this yourself, I suggest you start by having a read through the Developer Corner wiki page.

https://sangomakb.atlassian.net/wiki/spaces/FP/pages/10289341/Developer+Corner+Home#Getting-Involved

Thanks again for your time!

Regards,
Kapil Gupta
