### ISSUE TITLE
[bug]: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg)

### ISSUE THREAD

**Issue by Af0x** [FreePBX/sng_freepbx_debian_install#7]
### FreePBX Version

FreePBX 17

### Issue Description

When running apt update there is an error stating
`W: http://deb.freepbx.org/freepbx17-prod/dists/bookworm/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.`

### Operating Environment

Fresh Debian 12, FreePBX installation with Beta skript

**Comment by tdltdl** [comment]
Hi I am working on it as part of https://github.com/FreePBX/sng_freepbx_debian_install/issues/4

**Comment by chrsmj** [comment]
Duplicate of https://github.com/FreePBX/issue-tracker/issues/39

**Comment by tdltdl** [comment]
@kguptasangoma if #4 has been merged, could this be closed? The only warning I have left is about the "apt-key del".
