### ISSUE TITLE
[bug]: install script seems to error out with a gpg error

### ISSUE THREAD

**Issue by iansouth12** [FreePBX/sng_freepbx_debian_install#79]
### FreePBX Version

FreePBX 17

### Issue Description

My attempts to run the install script on Debian 12 seems to produce:

gpg: no valid OpenPGP data found.
2024-08-07 08:00:36 - Exiting script

### Operating Environment

Debian 12, attempting to install FreePBX 17

### Relevant log output

```shell
...
...
Archive for codename: bookworm components: main
More info: http://deb.freepbx.org/freepbx17-prod
Adding repository.
Adding deb entry to /etc/apt/sources.list.d/archive_uri-http_deb_freepbx_org_freepbx17-prod-bookworm.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/archive_uri-http_deb_freepbx_org_freepbx17-prod-bookworm.list
Hit:1 http://security.debian.org/debian-security bookworm-security InRelease
Hit:2 http://deb.debian.org/debian bookworm InRelease
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease
Hit:4 http://deb.freepbx.org/freepbx17-prod bookworm InRelease
Hit:5 https://packages.sury.org/php bookworm InRelease
Reading package lists...
Repository: 'deb [arch=amd64] http://deb.freepbx.org/freepbx17-prod bookworm main'
Description:
Archive for codename: bookworm components: main
More info: http://deb.freepbx.org/freepbx17-prod
Adding repository.
Found existing deb entry in /etc/apt/sources.list.d/archive_uri-http_deb_freepbx_org_freepbx17-prod-bookworm.list
Adding deb entry to /etc/apt/sources.list.d/archive_uri-http_deb_freepbx_org_freepbx17-prod-bookworm.list
Found existing deb-src entry in /etc/apt/sources.list.d/archive_uri-http_deb_freepbx_org_freepbx17-prod-bookworm.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/archive_uri-http_deb_freepbx_org_freepbx17-prod-bookworm.list
gpg: no valid OpenPGP data found.
2024-08-07 08:00:36 - Exiting script
```

**Comment by kguptasangoma** [comment]
`wget -qO - http://deb.freepbx.org/gpg/aptly-pubkey.asc | gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/freepbx.gpg`

If you try manually this command.

**Comment by iansouth12** [comment]
So, I didd that and got the same result when trying to re-run the install script:

Repository: 'deb [arch=amd64] http://deb.freepbx.org/freepbx17-prod bookworm main'
Description:
Archive for codename: bookworm components: main
More info: http://deb.freepbx.org/freepbx17-prod
Adding repository.
Found existing deb entry in /etc/apt/sources.list.d/archive_uri-http_deb_freepbx_org_freepbx17-prod-bookworm.list
Adding deb entry to /etc/apt/sources.list.d/archive_uri-http_deb_freepbx_org_freepbx17-prod-bookworm.list
Found existing deb-src entry in /etc/apt/sources.list.d/archive_uri-http_deb_freepbx_org_freepbx17-prod-bookworm.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/archive_uri-http_deb_freepbx_org_freepbx17-prod-bookworm.list
gpg: no valid OpenPGP data found.
2024-08-07 09:14:08 - Exiting script

**Comment by iansouth12** [comment]
[freepbx17-install-2024.08.07-09.28.11.log](https://github.com/user-attachments/files/16529308/freepbx17-install-2024.08.07-09.28.11.log)

**Comment by iansouth12** [comment]
I'm going to try something - Maybe because I've been trying to do this in VirtualBox on an intel Mac it could be an issue.  So, I do have an Ubuntu version of VirtualBox running here and beyond that I have an instance of UTM running on an Apple m2 processor I can try.

**Comment by iansouth12** [comment]
The plan will be - I will follow the instructions using a new bare bones install of debian 12 and see what happens

**Comment by iansouth12** [comment]
Ok, this step is wrong in the blog:

echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
service ssh restart
ip addr

"service" is an old term that is no longer valid as far as I know.  What I think you want is:

systemctl restart sshd

**Comment by iansouth12** [comment]
maybe even systemctl reload ssd

**Comment by iansouth12** [comment]
same result.
[freepbx17-install-2024.08.09-05.48.32.log](https://github.com/user-attachments/files/16559483/freepbx17-install-2024.08.09-05.48.32.log)

**Comment by iansouth12** [comment]
Really, I'm inclined to stick with version 16 and just remove internet access to/from the PBX at this point.

**Comment by iansouth12** [comment]
And honestly, until an reliable OVA can be built or the script gets modified there is no easy way forward.

**Comment by JoseGoncalves** [comment]
Hi @iansouth12. From what you report it seems that the FreePBX key is not being correctly imported into your system. Can you check what does the command `gpg --list-keys --keyring /etc/apt/trusted.gpg.d/freepbx.gpg` reports?

In my system it outputs:
```
/etc/apt/trusted.gpg.d/freepbx.gpg
----------------------------------
pub   rsa4096 2024-02-26 [SC] [expires: 2026-02-25]
      991C357C8A359D0382BC6E87C4DFE68FCE6DE186
uid           [ unknown] Aptly <aptly@sangoma.com>
sub   rsa4096 2024-02-26 [E] [expires: 2026-02-25]
```

You could also give it a try with the latest FreePBX 17 install script, as it had several updates recently.

**Comment by kguptasangoma** [comment]
closing as no response. Please feel free to reopen if the issue persists. thanks
