### ISSUE TITLE
[bug]: install does nothing, reports all up to date

### ISSUE THREAD

**Issue by QuinnEbert** [FreePBX/sng_freepbx_debian_install#80]
### FreePBX Version

FreePBX 17

### Issue Description

On a fresh Debian Bookworm VM, the installer always reports "Perfect! You're already running the latest version." and then immediately exits.  I am terrible at Bash scripting but it appears all it's doing is checking whether itself matches the known sha256 for itself.

### Operating Environment

Debian Bookworm amd64

### Relevant log output

```shell
root@vts-freepbx-v17:/tmp# ./sng_freepbx_debian_install.sh
Performing version check...
Perfect! You're already running the latest version.
```

**Comment by QuinnEbert** [comment]
Ah -- already figured out a (possible) root cause of this.  Initially, I didn't see where the logs were being placed (the `README.md` points to the wrong location -- logs are now under `/var/log/pbx` by default)

`hostname -f` for my VM was returning no value on stdout (only `hostname: Name or service not known` on stderr).  This should probably be handled and an appropriate error message returned.

I cannot guarantee I will come up with time to put together a pull request for a possible solution to this.  Hopefully me making you aware of the issue is helpful.

**Comment by QuinnEbert** [comment]
Confirmed: I created an equivalent PTR for the primary WAN interface's IP in `/etc/hosts` and all proceeded normally.

Please ensure you are appropriately handling cases where `hostname -f` are not returning valid results (I will be happy to provide a test VM and donate time on it so that you can recreate and patch this issue if you contact us via the contact methods posted at the website on my GitHub profile).

**Comment by kguptasangoma** [comment]
fixed the script to exit the hostname if not set properly.
