### ISSUE TITLE
[bug]: wget after install exiting

### ISSUE THREAD

**Issue by asarubbo** [FreePBX/sng_freepbx_debian_install#82]
### FreePBX Version

FreePBX 17

### Issue Description

I have launched the install documented [here](https://sangomakb.atlassian.net/wiki/spaces/FP/pages/230326391/FreePBX+17+Installation#How-to-execute-the-script).
After see the completion/exiting of the install, I still can see process like wget that are doing something:

```
freepbx-17 ~ # ps aux | grep wget
root      116022  0.0  0.0   2576   908 ?        S    07:36   0:00 sh -c wget --append-output=/var/log/asterisk/firmware_download_log http://ct.schmoozecom.net/digium.1.74.tar.gz -c -O /tftpboot/firmwaredownloads/digium.1.74.tar.gz
root      116023  0.3  0.1  13548  5264 ?        S    07:36   0:00 wget --append-output=/var/log/asterisk/firmware_download_log http://ct.schmoozecom.net/digium.1.74.tar.gz -c -O /tftpboot/firmwaredownloads/digium.1.74.tar.gz
```

That may have be interrupted if the user go for reboot.

### Operating Environment

Debian 12

**Comment by kguptasangoma** [comment]
Hi @asarubbo process to download the phone firmware by the endpoint manager module triggers in backend. firmware sizes are large so download may take some time.
If user reboot the machine in between then firmware will not be present and it will download again during the phone configuration process by endpoint manager.

Thank you for using Freepbx 17
Kapil
