### ISSUE TITLE
[bug]: https://packages.sury.org/php/apt.gpg error 451

### ISSUE THREAD

**Issue by KIvanov-1984** [FreePBX/sng_freepbx_debian_install#84]
### FreePBX Version

FreePBX 17

### Issue Description

Hello, I have an error when I install FreePBX 17, I have an error, when I try install

### Operating Environment

https://packages.sury.org/php/apt.gpg
Распознаётся packages.sury.org (packages.sury.org)… 146.59.69.202, 2001:41d0:605:ca00::1175:1
Подключение к packages.sury.org (packages.sury.org)|146.59.69.202|:443... соединение установлено.
HTTP-запрос отправлен. Ожидание ответа… 451
2024-08-15 13:35:13 ОШИБКА 451: (нет описания).

### Relevant log output

```shell
https://packages.sury.org/php/apt.gpg
Распознаётся packages.sury.org (packages.sury.org)… 146.59.69.202, 2001:41d0:605:ca00::1175:1
Подключение к packages.sury.org (packages.sury.org)|146.59.69.202|:443... соединение установлено.
HTTP-запрос отправлен. Ожидание ответа… 451
2024-08-15 13:35:13 ОШИБКА 451: (нет описания).
```

**Comment by jestgraff** [comment]
Видимо, с российских IP-адресов нет доступа. Попробуй установить с использованием VPN

**Comment by kguptasangoma** [comment]
Are you able to execute below command manually? 

`wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg`

**Comment by KIvanov-1984** [comment]
I have this error with any files on this web server

**Comment by kguptasangoma** [comment]
removed sury packages dependency from the script and now using debian upstream itself for downloading the php packages.
