### ISSUE TITLE
[bug]: FreePBX cannot determine if Asterisk is running or it frequently crashes.

### ISSUE THREAD

**Issue by BlindMaster24** [FreePBX/sng_freepbx_debian_install#85]
### FreePBX Version

FreePBX 17

### Issue Description

When installing FreePBX using the script, the SangomaConnect module does not install due to "Asterisk not connected", even though it sometimes works but asks to change permissions on folders or something like that. Because of this, an error occurs in the script. When executing start or restart using fwconsole, FreePBX cannot connect to Asterisk, even though it tries to start it for 1 minute.

### Operating Environment

The latest version of Debian 12

### Relevant log output

```shell
I've explained everything in the comment on the issue. I don't think it's worth sending the line saying that FreePBX can't connect to Asterisk.
```

**Comment by BlindMaster24** [comment]
Asterisk requests permission changes on the folders when started manually under the Asterisk user; however, Asterisk still starts. When the script runs again, the SangomaConnect module is installed, but FreePBX does not see the running process after executing fwconsole restart, eg.

**Comment by kguptasangoma** [comment]
Hi @BlindMaster24 We have not noticed this kind of error so any logs or details would be helpful.

Like, when you see the error, just try to connect with the asterisk via "asterisk -rvv"  to confirm asterisk is running and also password for the freepbx is same as per the asterisk configured users.

**Comment by BlindMaster24** [comment]
Unable to access the running directory (Permission denied).  Changing to '/' for compatibility.                         
Connected to Asterisk 21.4.1 currently running on pbx (pid = 113669)                                                    



I simply executed the commands:
su asterisk  
asterisk -rvvv


systemctl status apache2

Aug 16 12:26:16 pbx.sherserver.ru systemd[1]: Starting apache2.service - The Apache HTTP Server...                      
Aug 16 12:26:16 pbx.sherserver.ru systemd[1]: Started apache2.service - The Apache HTTP Server.                         
Aug 18 00:00:08 pbx.sherserver.ru systemd[1]: Reloading apache2.service - The Apache HTTP Server...                     
Aug 18 00:00:09 pbx.sherserver.ru systemd[1]: Reloaded apache2.service - The Apache HTTP Server.                        
Aug 19 00:00:04 pbx.sherserver.ru systemd[1]: Reloading apache2.service - The Apache HTTP Server...                     
Aug 19 00:00:05 pbx.sherserver.ru systemd[1]: Reloaded apache2.service - The Apache HTTP Server.




I couldn't access the web interface. I checked the configurations. It only includes includes, but there are no users or anything. It's as if the system really didn't start. Initially, I just ran the script, and it seems like Asterisk is starting, but the PBX doesn't see it. It's strange, but it's running, and right now the web interface is completely empty. I don't see any login page, and I've never logged in there. I just got a module installation error, and that's it.




It's just a test virtual server. I can't figure out what the problem is because, according to the script code, everything should be fine, but it seems it's not.

I can provide the installation logs if needed.

**Comment by BlindMaster24** [comment]
;--------------------------------------------------------------------------------;
;          Do NOT edit this file as it is auto-generated by FreePBX.             ;
;--------------------------------------------------------------------------------;
; For information on adding additional paramaters to this file, please visit the ;
; FreePBX.org wiki page, or ask on IRC. This file was created by the new FreePBX ;
; BMO - Big Module Object. Any similarity in naming with BMO from Adventure Time ;
; is totally deliberate.                                                         ;
;--------------------------------------------------------------------------------;

[0]
#include pjsip_custom.conf
#include pjsip.transports.conf
#include pjsip.transports_custom_post.conf
#include pjsip.endpoint.conf
#include pjsip.endpoint_custom_post.conf
#include pjsip.aor.conf
#include pjsip.aor_custom_post.conf
#include pjsip.auth.conf
#include pjsip.auth_custom_post.conf
#include pjsip.registration.conf
#include pjsip.registration_custom_post.conf
#include pjsip.identify.conf
#include pjsip.identify_custom_post.conf

[global]
type=global
user_agent=FPBX-17.0.19.1(20.8.1)
use_callerid_contact=no
keep_alive_interval=90
taskprocessor_overload_trigger=pjsip_only
#include pjsip_custom_post.conf

**Comment by BlindMaster24** [comment]
Active: failed (Result: exit-code) since Mon 2024-08-19 12:08:35 MSK; 49s ago                                      
    Process: 1326895 ExecStart=/usr/sbin/fwconsole start (code=exited, status=1/FAILURE)                                
   Main PID: 1326895 (code=exited, status=1/FAILURE)                                                                    
        CPU: 8.208s                                                                                                     
                                                                                                                        
Aug 19 12:08:35 pbx.sherserver.ru fwconsole[1326895]: [---------------->-----------] 45 secs                            
Aug 19 12:08:35 pbx.sherserver.ru fwconsole[1326895]: In Start.class.php line 194:                                      
Aug 19 12:08:35 pbx.sherserver.ru fwconsole[1326895]:                                                                   
Aug 19 12:08:35 pbx.sherserver.ru fwconsole[1326895]:   Unable to connect to Asterisk. Did it start?                    
Aug 19 12:08:35 pbx.sherserver.ru fwconsole[1326895]:                                                                   
Aug 19 12:08:35 pbx.sherserver.ru fwconsole[1326895]: start [--pre] [--post] [--skipchown] [--] [<args>...]             
Aug 19 12:08:35 pbx.sherserver.ru systemd[1]: freepbx.service: Main process exited, code=exited, status=1/FAILURE       
Aug 19 12:08:35 pbx.sherserver.ru systemd[1]: freepbx.service: Failed with result 'exit-code'.                          
Aug 19 12:08:35 pbx.sherserver.ru systemd[1]: Failed to start freepbx.service - FreePBX VoIP Server.                    
Aug 19 12:08:35 pbx.sherserver.ru systemd[1]: freepbx.service: Consumed 8.208s CPU time.

**Comment by BlindMaster24** [comment]
I have news. Everything works fine when downloading the ISO of the operating system as you advised. However, when installing the system through the hosting control panel, as I did, Asterisk does not start for some reason. Can you explain what the differences might be and why it could be this way? I will conduct a few tests, but the machine where the clean operating system was installed works perfectly. Since I am a visually impaired user, it's impossible to install the operating system on the server blindly, especially since it's Debian. That's why I used the hosting control panel, but unfortunately, it doesn't work for some reason. Can you explain what the issue might be?

**Comment by BlindMaster24** [comment]
Ubuntu has an SSH Install mode and it suits me. Therefore, the question is whether the script can be adapted for Ubuntu, or will there be a separate version for Ubuntu in the future? After all, these are two main systems, considering that Ubuntu is a fork of Debian, I believe there should be a script for it or they should be compatible with each other.

**Comment by kguptasangoma** [comment]
Hi @BlindMaster24 thanks for sharing more information, right now our main focus is on vanilla debian os. 

Once Debian OS is stable then we could try to focus on Ubuntu or any other Debian based systems.

However, script can easily modify to add support for the ubuntu so feel free to provide your patches for ubuntu.

**Comment by BlindMaster24** [comment]
Hi, @kguptasangoma Good idea. I might get around to it soon. Thank you. 

But do you have any ideas why the installation might not be proceeding correctly, in your opinion?

**Comment by BlindMaster24** [comment]
I've got some news! Here's what the logs for Asterisk say on the virtual machine where there was an installation error:

[2024-08-19 14:20:24] WARNING[111573] res_odbc.c: res_odbc: Error SQLConnect=-1 errno=1045 [unixODBC][ma-3.1.15] Access denied for user 'freepbxuser'@'localhost' (using password: YES)  
[2024-08-19 14:20:24] NOTICE[111573] res_odbc.c: Registered ODBC class 'asteriskcdrdb' dsn->[MySQL-asteriskcdrdb]



And



Aug 19 14:20:48 pbx.sherserver.ru mariadbd[112284]: 2024-08-19 14:20:48 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
Aug 19 14:20:48 pbx.sherserver.ru mariadbd[112284]: 2024-08-19 14:20:48 0 [Note] Server socket created on IP: '127.0.0.1'.
Aug 19 14:20:48 pbx.sherserver.ru mariadbd[112284]: 2024-08-19 14:20:48 0 [Note] /usr/sbin/mariadbd: ready for connections.
Aug 19 14:20:48 pbx.sherserver.ru mariadbd[112284]: Version: '10.11.6-MariaDB-0+deb12u1'  socket: '/run/mysqld/mysqld.sock'  port: 3306  Debian 12
Aug 19 14:20:48 pbx.sherserver.ru systemd[1]: Started mariadb.service - MariaDB 10.11.6 database server.
Aug 19 14:20:48 pbx.sherserver.ru /etc/mysql/debian-start[112301]: Upgrading MySQL tables if necessary.
Aug 19 14:20:48 pbx.sherserver.ru mariadbd[112284]: 2024-08-19 14:20:48 0 [Note] InnoDB: Buffer pool(s) load completed at 240819 14:20:48
Aug 19 14:21:01 pbx.sherserver.ru mariadbd[112284]: 2024-08-19 14:21:01 40 [Warning] Access denied for user 'freepbxuser'@'localhost' (using password: YES)
Aug 19 14:21:01 pbx.sherserver.ru mariadbd[112284]: 2024-08-19 14:21:01 41 [Warning] Access denied for user 'freepbxuser'@'localhost' (using password: YES)
Aug 19 14:21:02 pbx.sherserver.ru mariadbd[112284]: 2024-08-19 14:21:02 44 [Warning] Access denied for user 'freepbxuser'@'localhost' (using password: YES)

**Comment by kguptasangoma** [comment]
`Aug 19 14:21:01 pbx.sherserver.ru mariadbd[112284]: 2024-08-19 14:21:01 40 [Warning] Access denied for user 'freepbxuser'@'localhost' (using password: YES)`

Looks like you have to set proper permissions for the user to access the db.

**Comment by kguptasangoma** [comment]
Also @BlindMaster24 

This system is setup for bug tracking only and does not handle support request or general questions.

If this is a PBXact issue or related to a commercial product, please open a support ticket at  https://help.sangoma.com/

For FreePBX support or general questions, you have the following options:

Self Service:
https://sangomakb.atlassian.net/wiki/spaces/FP/overview
Community Forums with search
http://community.freepbx.org  
Paid support.
https://help.sangoma.com/

Thank you for using FreePBX
Kapil Gupta

**Comment by kguptasangoma** [comment]
Please raise thread in the community forum for the non Debian installation so community can help/guide you. 

Thank you for using Freepbx 17
Kapil
