### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by salmanaalfariz01** [FreePBX/sng_freepbx_debian_install#88]
### FreePBX Version

FreePBX 17

### Issue Description

![Screenshot 2024-08-21 200121](https://github.com/user-attachments/assets/14d5f1f5-b984-40df-8efd-60867f818b31)

### Operating Environment

![Screenshot 2024-08-21 200121](https://github.com/user-attachments/assets/b5f75cd9-25f4-42ad-9b2c-5efdaf386e70)

**Comment by kguptasangoma** [comment]
its failing to install the sysadmin module,  please check the error in the log.

**Comment by kguptasangoma** [comment]
please check the log file for the error and also /var/log/syslog if you find any low memory related issues.
